server:
  addr: "localhost:7923"
  port: 7293
  timeout: "5s"

postgres:
  host: "localhost"
  port: 6128
  dbname: "messenger"
  username: "postgres"
  ssl_mode: "disable"

redis:
  addr: "localhost:6379"
  db: 0
  max_retries: 3
  dial_timeout: "10s"
  timeout: "5s"


env: "local"