server:
  addr: "localhost"
  port: 7293
  timeout: "5s"

postgres:
  host: "localhost"
  port: 6128
  dbname: "messenger"
  username: "postgres"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379

env: "local"